

# manual setting
max_frames: 32  
resolution: [512, 768]  
round: 5
ddim_timesteps: 30  
seed: 13
test_list_path: [
  [2, "data/images/1.jpg", "data/saved_pose/dance_1","data/saved_frames/dance_1","data/saved_pkl/dance_1.pkl", 14], # seed 14
  [2, "data/images/4.png", "data/saved_pose/dance_1","data/saved_frames/dance_1","data/saved_pkl/dance_1.pkl", 14], # seed 14
  [2, "data/images/3.jpeg", "data/saved_pose/dance_2","data/saved_frames/dance_2","data/saved_pkl/dance_2.pkl", 13], # seed 13
  [2, "data/images/10.jpeg", "data/saved_pose/dance_2","data/saved_frames/dance_2","data/saved_pkl/dance_2.pkl", 14], # 
  [2, "data/images/zhu.png", "data/saved_pose/dance_3","data/saved_frames/dance_3","data/saved_pkl/dance_3.pkl", 14],
  [2, "data/images/5.jpeg", "data/saved_pose/dance_3","data/saved_frames/dance_3","data/saved_pkl/dance_3.pkl", 14],
  [1, "data/images/2.jpeg", "data/saved_pose/dance_3_right","data/saved_frames/dance_3_right","data/saved_pkl/dance_3_right.pkl", 13], # seed 13 
  [4, "data/images/7.jpeg", "data/saved_pose/ubc","data/saved_frames/ubc","data/saved_pkl/ubc.pkl", 14],
]


log_dir: 'results' # save dir

test_model:  checkpoints/animate-x_ckpt.pth  
partial_keys: [
                    ['image','local_image', 'dwpose','pose_embeddings'], 
                ]




# default settings
TASK_TYPE: inference_animate_x_entrance
use_fp16: True
guide_scale: 2.5
vit_resolution: [224, 224]
use_fp16: True
batch_size: 1
latent_random_ref: True
chunk_size: 2
decoder_bs: 2
scale: 8
use_fps_condition: False

embedder: {
    'type': 'FrozenOpenCLIPTextVisualEmbedder',
    'layer': 'penultimate',
    'pretrained':  'checkpoints/open_clip_pytorch_model.bin' 
}

auto_encoder: {
    'type': 'AutoencoderKL',
    'ddconfig': {
        'double_z': True, 
        'z_channels': 4,
        'resolution': 256, 
        'in_channels': 3,
        'out_ch': 3, 
        'ch': 128, 
        'ch_mult': [1, 2, 4, 4],
        'num_res_blocks': 2, 
        'attn_resolutions': [], 
        'dropout': 0.0,
        'video_kernel_size': [3, 1, 1]
    },
    'embed_dim': 4,
    'pretrained': 'checkpoints/v2-1_512-ema-pruned.ckpt'
} 


UNet: {
    'type': 'UNetSD_Animate_X',
    'config': None,
    'in_dim': 4,
    'num': 0,
    'no_hand': True,
    'dim': 320,
    'y_dim': 1024,
    'context_dim': 1024,
    'out_dim': 4,
    'dim_mult': [1, 2, 4, 4],
    'num_heads': 8,
    'head_dim': 64,
    'num_res_blocks': 2,
    'dropout': 0.1,
    'temporal_attention': True,
    'num_tokens': 4,
    'temporal_attn_times': 1,
    'use_checkpoint': True,
    'use_fps_condition': False,
    'use_sim_mask': False
}
video_compositions: ['image', 'local_image', 'dwpose', 'randomref', 'randomref_pose', 'pose_embedding']
Diffusion: {
    'type': 'DiffusionDDIM',
    'schedule': 'linear_sd', 
    'schedule_param': {
        'num_timesteps': 1000,
        "init_beta": 0.00085, 
        "last_beta": 0.0120,
        'zero_terminal_snr': True,
    },
    'mean_type': 'v',
    'loss_type': 'mse',
    'var_type': 'fixed_small',
    'rescale_timesteps': False,
    'noise_strength': 0.1
}
use_DiffusionDPM: False
CPU_CLIP_VAE: True

